import { Component } from '@angular/core';

interface ErrorCode {
  code: string;
  description: string;
}

@Component({
  selector: 'app-error-codes-modal',
  standalone: false,
  templateUrl: './error-codes-modal.component.html',
  styleUrls: ['./error-codes-modal.component.scss']
})
export class ErrorCodesModalComponent {
  showModal = false;
  
  // Accordion states
  businessExpanded = false;
  validationExpanded = false;
  vposExpanded = false;

  // Business Error Codes
  businessErrorCodes: ErrorCode[] = [
    { code: 'AUTHENTICATION_FAILED', description: 'Kimlik doğrulama başarısız oldu' },
    { code: 'INVALID_ACCOUNT_KEY_IN_TOKEN', description: 'İstekteki account key, tokendaki account key değerinden farklıdır' },
    { code: 'INVALID_MERCHANT_ID_IN_TOKEN', description: 'İstekteki merchant id, tokendaki merchant id değerinden farklıdır' },
    { code: 'INVALID_USER_ID_IN_TOKEN', description: 'İstekteki user id, tokendaki user id değerinden farklıdır' },
    { code: 'INVALID_MSISDN_VALIDATED_PARAM_IN_TOKEN', description: 'İstekteki msisdn validated parametresi, tokendaki msisdn validated parametresinden farklıdır' },
    { code: 'INVALID_AUTHENTICATION_METHOD_IN_TOKEN', description: 'İstekteki authentication method, tokendaki authentication method değerinden farklıdır' },
    { code: 'INVALID_SECURE_3D_MODEL_IN_TOKEN', description: 'İstekteki secure 3d model, tokendaki secure 3d model değerinden farklıdır' },
    { code: 'INVALID_BANK_ICA_IN_TOKEN', description: 'İstekteki bank ica, tokendaki bank ica değerinden farklıdır' },
    { code: 'INVALID_TERMINAL_INFO_IN_TOKEN', description: 'İstekteki terminal bilgileri, tokendaki terminal bilgilerinden farklıdır' },
    { code: 'INVALID_FIELD_TYPE', description: 'Alanın değeri beklenen alan tipi ile örtüşmüyor' },
    { code: 'INVALID_ORDER_NO_IN_TOKEN', description: 'İstekteki sipariş numarası, tokendaki sipariş numarası değerinden farklıdır' },
    { code: 'INVALID_AMOUNT_IN_TOKEN', description: 'İstekteki tutar, tokendaki tutar değerinden farklıdır' },
    { code: 'INVALID_CREDIT_BASKET_IN_TOKEN', description: 'İstekteki credit basket, tokendaki credit basket değerinden farklıdır' },
    { code: 'INVALID_CAMPAING_CODE_IN_TOKEN', description: 'İstekteki kampanya kodu, tokendaki kampanya kodu değerinden farklıdır' },
    { code: 'INVALID_CURRENCY_CODE_IN_TOKEN', description: 'İstekteki para kodu, tokendaki para kodu değerinden farklıdır' },
    { code: 'INVALID_IP_ADDRESS', description: 'Ip adresi geçersiz' },
    { code: 'CLIENT_IS_NOT_AUTHENTICATED', description: 'Merchant yetkili değil' },
    { code: 'MERCHANT_NOT_FOUND', description: 'İş yeri bulunamadı' },
    { code: 'ACCOUNT_NOT_FOUND', description: 'Hesap bulunamadı' },
    { code: 'CARD_NOT_FOUND', description: 'Kart bulunamadı' },
    { code: 'CARD_ALREADY_EXISTS', description: 'Kart bulunamadı' },
    { code: 'USER_NOT_FOUND', description: 'Kullanıcı bulunamadı' },
    { code: 'ACCOUNT_NOT_LINKED_TO_MERCHANT', description: 'Hesap iş yerine bağlı değil' },
    { code: 'ACCOUNT_IS_ALREADY_LINKED_TO_THIS_MERCHANT', description: 'Hesap halihazırda iş yerine linkli' },
    { code: 'MERCHANT_USER_ID_ALREADY_IN_USE', description: 'Bu kullanıcı numarası zaten mevcut. Lütfen farklı bir değer giriniz' },
    { code: 'MAX_NUMBER_OF_ACCOUNTS_REACHED', description: 'Belirtilen kart halihazırda izin verilen azami sayıda hesaba ekli durumda' },
    { code: 'MAX_NUMBER_OF_CARDS_REACHED', description: 'Bu hesap için maksimum kart sayısına ulaşıldı' },
    { code: 'MERCHANT_ID_MISMATCH', description: 'İstekte gönderilen iş yeri numarası, ilk işlemde gönderilen iş yeri numarasından farklı' },
    { code: 'ACCOUNT_IS_BLOCKED', description: 'Hesap bloke edilmiş' },
    { code: 'CARD_ALIAS_CANNOT_CONTAIN_CARD_NUMBER', description: 'Kart adı kart numarası içeremez' },
    { code: 'ACCOUNT_IS_REMOVED', description: 'Hesap silindi' },
    { code: 'ACCOUNT_IS_REMOVED_DUE_TO_OTP_FAILED_FOR_ALL_CARDS', description: 'Herhangi bir kart için otp doğrulaması yapılamadığından hesap silindi' },
    { code: 'CURRENT_USER_ID_IS_REQUIRED', description: 'Mevcut iş yeri kullanıcı numarası gerekli' },
    { code: 'FRAUD_DETECTED_DUE_TO_REPETITIVE_DELETION', description: 'Art arda gelen çok sayıda silme işlemi sebebiyle dolandırıcılık tespit edildi' },
    { code: 'MSISDN_HAS_BEEN_CHANGED', description: 'MSISDN güncel değil' },
    { code: 'EXPIRED_CARD_CANNOT_BE_SET_AS_DEFAULT', description: 'Son kullanım tarihi geçmiş olan kart, varsayılan kart olarak belirlenemez' },
    { code: 'NOT_SUPPORTED_CARD_AUTHORITY', description: 'Belirtilen karta ait BIN ödeme işlemleri için yetkilendirilmemiş' },
    { code: 'ISSUER_ICA_NUMBER_NOT_FOUND', description: 'Issuer ica numarası bulunamadı' },
    { code: 'CARD_TYPE_IS_NOT_SUPPORTED', description: 'Kart türü desteklenmiyor' },
    { code: 'RECURRING_PAYMENT_ORDER_ALREADY_EXISTS', description: 'Düzenli ödeme emri zaten mevcut' },
    { code: 'RECURRING_PAYMENT_ORDER_NOT_FOUND', description: 'Düzenli ödeme emri bulunamadı' },
    { code: 'RECURRING_PAYMENT_ORDER_HAS_EXPIRED', description: 'Düzenli ödeme emrinin süresi dolmuştur' },
    { code: 'RECURRING_PAYMENTS_NOT_SUPPORTED_BY_ISSUER', description: 'Yinelenen ödeme yöntemi Issuer banka tarafından desteklenmiyor' },
    { code: 'RECURRING_ORDER_NOT_VALIDATED', description: 'Yinelenen ödeme doğrulaması sağlanamadı' },
    { code: 'RECURRING_ORDER_NOT_FOUND', description: 'Tekrarlı ödeme talimatı bulunamadı' },
    { code: 'RECURRING_AMOUNT_THRESHOLD_EXCEEDED', description: 'Tekrarlı ödeme talimatı tutarı aşıldı' },
    { code: 'RECURRING_EXPIRE_DATE_EXCEEDED', description: 'Tekrarlı ödeme talimatı sona ermiş' },
    { code: 'RECURRING_PRE_AUTH_FLOW_NOT_FOUND', description: 'Tekrarlı ödeme ön provizyon işlemi bulunamadı' },
    { code: 'RECURRING_POST_AUTH_ALREADY_EXIST', description: 'Tekrarlı ödeme provizyon kapama işlemi mevcut' },
    { code: 'CARD_NUMBER_IS_NOT_VALID', description: 'Kart numarası hatalıdır' },
    { code: 'OLD_CARD_NOT_FOUND', description: 'Eski kart bulunamadı' },
    { code: 'NEW_CARD_ALREADY_EXISTS', description: 'Yeni kart sistemde kayıtlıdır' },
    { code: 'NO_PERMISSON_FOR_THIS_BIN', description: 'Bu bin için izin yok' },
    { code: 'CURRENT_USER_ID_NOT_FOUND', description: 'Mevcut iş yeri kullanıcı numarası bulunamadı' },
    { code: 'BANK_DOES_NOT_SUPPORT_OTP', description: 'Banka otp desteklemiyor' },
    { code: 'CARD_ALIAS_ALREADY_IN_USE', description: 'Kart adı başka bir kartta kullanılmaktadır. Lütfen başka bir kart adı girin' },
    { code: 'CAN_NOT_DECRYPT_CARDNUMBER', description: 'Kart numarası çözülemedi' },
    { code: 'CARDNUMBER_RESOLVED_TO_NULL', description: 'Kart numarası boş olarak çözüldü' },
    { code: 'MERCHANT_DOES_NOT_HAVE_ACCESS', description: 'İş yerinin kullanıcı hesabına erişim yetkisi bulunmuyor' },
    { code: 'PAYMENT_IS_NOT_VERIFIED', description: 'Ödeme doğrulanamadı' },
    { code: 'TERMINAL_NOT_FOUND', description: 'Sanal POS tanımı bulunamadı' },
    { code: 'PRE_AUTH_FLOW_NOT_FOUND', description: 'Ön provizyon işlemi bulunamadı' },
    { code: 'BIN_NUMBER_NOT_FOUND', description: 'Bin numarası bulunamadı' },
    { code: 'ACCOUNT_DOES_NOT_HAVE_ANY_RECIPIENT_CARD', description: 'Hesapta kayıtlı alıcı kart bulunmamaktadır' },
    { code: 'RECIPIENT_CARD_NOT_FOUND', description: 'Alıcı kart bulunamadı' },
    { code: 'ONLY_MASTERPASS_ACCOUNTS_CAN_USE_THIS_SERVICE', description: 'Sadece masterpass hesapları bu servisi kullanabilir' },
    { code: 'SECURE_3D_SUPPORTING_VPOS_NOT_FOUND', description: '3d işlem destekleyen hiç bir terminal bulunamadı' },
    { code: 'CVC_CANNOT_BE_DECRYPTED', description: 'CVC çözülemedi' },
    { code: 'NO_ALTERNATE_TERMINAL', description: 'Yedek sanal POS mevcut değil' },
    { code: 'ORDER_NOT_FOUND', description: 'İstekte gönderilen bilgilere sahip bir sipariş bulunamadı' },
    { code: 'ICA_NUMBER_NOT_FOUND_IN_TERMINAL_GROUP', description: 'Gönderilen ica numarası terminal grubun içinde olmalıdır' },
    { code: 'ACQUIRER_DOES_NOT_SUPPORTED_3D_MODEL', description: 'Banka 3d modeli desteklememektedir' },
    { code: 'ACQUIRER_DOES_NOT_SUPPORTED_3D_PAY_MODEL', description: 'Banka 3d Pay modeli desteklememektedir' },
    { code: 'INVALID_MONEY_SEND_TYPE', description: 'Geçersiz para transferi tipi' },
    { code: 'OCT_NOT_DEFINED_FOR_MONEY_SEND', description: 'Para transferi işlemi için OCT tanımlı değil' },
    { code: 'BANK_IS_BLOCKED', description: 'Banka bloklu ve diğer bankalar denenemiyor' },
    { code: 'VPOS_INTEGRATION_SERVICE_NOT_AVAILABLE', description: 'Bu operasyon için ilgili bankada vpos entegrasyonu mevcut değildir' },
    { code: 'REQUEST_CONTAINS_INVALID_SECURITY_TYPE', description: 'Request body\'deki güvenlik türü işlem için uygun değildir' },
    { code: 'ERR_3D_AUTHENTICATION', description: '3D doğrulaması başarısız' },
    { code: 'INVALID_RTA', description: 'Rta değeri geçersiz' },
    { code: 'OTP_IS_NOT_VALID', description: 'Tek seferlik şifre geçersiz' },
    { code: 'BANK_DOES_NOT_SUPPORT_3D', description: 'Banka 3d desteklemiyor' },
    { code: 'ERR_YOU_CAN_NOT_CALL_OTP_SERVICE_ONE_MORE_TIME', description: 'Tek kullanımlık şifre talep etme limitine ulaştınız. Lütfen daha sonra tekrar deneyiniz' },
    { code: 'TOKEN_ALREADY_USED', description: 'Token zaten kullanılmış' },
    { code: 'AUTHENTICATION_METHOD_NOT_FOUND', description: 'Doğrulama yöntemi bulunamadı' },
    { code: 'CITIZENSHIP_ALREADY_VERIFIED', description: 'Kimlik numarası daha önce doğrulandı' },
    { code: 'INVALID_URI_FORMAT', description: 'Url formatı hatalı' },
    { code: 'ERROR_CALLED_OTP_SERVICE_ONE_MORE_TIME_BEFORE_TIMEOUT_EXPIRED', description: 'Süresi dolmadan otp gönderme servisini çağıramazsınız' },
    { code: 'CARD_DOES_NOT_3DS_ENROLLED', description: 'Kart 3D kayıtlı değil' },
    { code: 'BANK_DOES_NOT_SUPPORT_OTP_VALIDATION', description: 'Banka otp validasyonunu desteklemiyor' },
    { code: 'ORDER_LENGTH_MISMATCH', description: 'Sipariş listesi uzunlukları uyuşmuyor' },
    { code: 'ORDER_PRODUCT_DETAILS_EMPTY', description: 'Sipariş ürün detayları boş' },
    { code: 'TOKEN_HAS_EXPIRED', description: 'Tokenın süresi doldu' },
    { code: 'VPOS_TIMEOUT_ERROR', description: 'Sanal Pos cevap vermiyor veya bağlantıda bir sorun var' },
    { code: 'CREDIT_CONNECTION_ERROR', description: 'Kredi bağlantı hatası' },
    { code: 'CONNECTION_ERROR', description: 'Servis cevap vermiyor veya bağlantıda bir sorun var' },
    { code: 'VPOS_CONNECTION_ERROR', description: 'Sanal Pos cevap vermiyor veya bağlantıda bir sorun var' },
    { code: 'NOT_IMPLEMENTED_ERROR', description: 'Servis implementasyonu yapılmadı' },
    { code: 'UNEXPECTED_ERROR', description: 'Talebinizi işlerken beklenmeyen bir hata oluştu' },
    { code: 'CAN_NOT_DECRYPT_PASSWORD', description: 'Password değeri decrypt edilemedi' }
  ];

  // Validation Error Codes
  validationErrorCodes: ErrorCode[] = [
    { code: 'VALIDATION_FAILED', description: 'Validasyon yapılamadı' },
    { code: 'MERCHANT_USER_ID_IS_REQUIRED', description: 'İş yeri kullanıcı numarası gerekli' },
    { code: 'MERCHANT_USER_ID_MAX_LENGTH_EXCEEDED', description: 'İş yeri kullanıcı numarası 101 karakterden kısa olmalı' },
    { code: 'MERCHANT_USER_ID_MISMATCH', description: 'Üye işyeri kullanıcı numarası eşleşmiyor' },
    { code: 'ACCOUNT_KEY_IS_NOT_VALID', description: 'Telefon numarası geçerli değil' },
    { code: 'ACCOUNT_KEY_IS_REQUIRED', description: 'Hesap anahtarı gerekli' },
    { code: 'ACCOUNT_KEY_MAX_LENGTH_EXCEEDED', description: 'Hesap anahtarı 21 haneden kısa olmalı' },
    { code: 'ACCOUNT_KEY_TYPE_IS_NOT_VALID', description: 'Hesap anahtarı tipi geçerli değil' },
    { code: 'AMOUNT_IS_REQUIRED', description: 'İşlem tutarı gerekli' },
    { code: 'AMOUNT_IS_NOT_VALID', description: 'İşlem tutarı geçersiz' },
    { code: 'AMOUNT_MAX_LIMIT_EXCEEDED', description: 'Amount 10 haneden kısa olmalı' },
    { code: 'CARD_ALIAS_IS_REQUIRED', description: 'Kart adı gerekli' },
    { code: 'CARD_ALIAS_MAX_LENGTH_EXCEEDED', description: 'Kart adı 41 karakterden kısa olmalı' },
    { code: 'CARD_HOLDER_NAME_CANNOT_CONTAIN_CARD_NUMBER', description: 'Kart sahibi adı kart numarası içeremez' },
    { code: 'CARD_HOLDER_NAME_MAX_LENGTH_EXCEEDED', description: 'Kart sahibi adı 51 karakterden kısa olmalı' },
    { code: 'CARD_NUMBER_IS_REQUIRED', description: 'Kart numarası gerekli' },
    { code: 'CARD_NUMBER_MAX_LENGTH_EXCEEDED', description: 'Kart numarası 500 karakterden kısa olmalıdır' },
    { code: 'EXPIRY_DATE_IS_NOT_VALID', description: 'Geçerlilik tarihi YYAA formatında olmalı' },
    { code: 'EXPIRY_DATE_IS_REQUIRED', description: 'Geçerlilik tarihi gerekli' },
    { code: 'EXPIRY_DATE_LENGTH_IS_NOT_VALID', description: 'Geçerlilik tarihi 4 haneli olarak girilmeli' },
    { code: 'RECURRING_EXPIRE_DATE_IS_NOT_VALID', description: 'Geçerlilik tarihi yyyyMMdd formatında olmalı' },
    { code: 'RECURRING_EXPIRE_DATE_LENGTH_IS_NOT_VALID', description: 'Geçerlilik tarihi 8 haneli olarak girilmeli' },
    { code: 'RECURRING_EXPIRE_DATE_MUST_BE_FUTURE_DATE', description: 'Geçerlilik tarihi ileri bir tarih olmalıdır' },
    { code: 'MERCHANT_ID_IS_NOT_VALID', description: 'İş yeri numarası geçersiz' },
    { code: 'MERCHANT_ID_IS_REQUIRED', description: 'İş yeri numarası gerekli' },
    { code: 'MERCHANT_ID_MAX_LENGTH_EXCEEDED', description: 'Üye işyeri no maksimum uzunlugu geçmektedir' },
    { code: 'OLD_AND_NEW_VALUES_CANNOT_BE_EQUAL', description: 'Eski ve yeni değerler birbirinden farklı olmalı' },
    { code: 'REQUEST_REFERENCE_NUMBER_IS_NOT_VALID', description: 'İstek referans numarası geçerli değil' },
    { code: 'REQUEST_REFERENCE_NUMBER_IS_REQUIRED', description: 'İstek referans numarası gerekli' },
    { code: 'REQUEST_REFERENCE_NUMBER_MAX_LENGTH_EXCEEDED', description: 'İstek referans numarası maksimum uzunlugu geçmektedir' },
    { code: 'SDK_VERSION_MAX_LENGTH_EXCEEDED', description: 'SDK versiyonu 17 karakterden kısa olmalı' },
    { code: 'SOURCE_CHANNEL_IS_NOT_VALID', description: 'Kaynak kanal geçerli değil' },
    { code: 'MSISDN_IS_REQUIRED', description: 'Msisdn gerekli' },
    { code: 'MSISDN_IS_NOT_VALID', description: 'Msisdn geçersiz' },
    { code: 'SOURCE_CHANNEL_IS_NOT_AUTHORIZED', description: 'Kaynak kanal yetkili değil' },
    { code: 'TOKEN_IS_REQUIRED', description: 'Token gerekli' },
    { code: 'TOKEN_IS_NOT_VALID', description: 'Token geçersiz' },
    { code: 'PRODUCT_ID_MAX_LENGTH_EXCEEDED', description: 'Ürün numarası 33 karakterden kısa olmalıdır' },
    { code: 'ENCRYPTED_CARD_NUMBER_AND_EXPIRE_DATE_IS_REQUIRED', description: 'Şifreli kart numarası ve son kullanma tarihi gereklidir' },
    { code: 'CREDIT_TOKEN_IS_REQUIRED', description: 'Kredi anahtarı zorunludur' },
    { code: 'CREDIT_INSTALLMENT_ID_IS_REQUIRED', description: 'Kredi taksit sayısı zorunludur' },
    { code: 'CREDIT_APPROVEMENT_LIST_IS_REQUIRED', description: 'Kredi onay listesi zorunludur' },
    { code: 'CREDIT_CARD_DATA_IS_REQUIRED', description: 'Kredi işlemi kart bilgisi zorunludur' },
    { code: 'CREDIT_ENCRYPTED_PAN_IS_REQUIRED', description: 'Kredi işlemi şifreli kart bilgisi zorunludur' },
    { code: 'CREDIT_ENCRYPTED_PAN_MAX_LENGTH_EXCEEDED', description: 'Kredi işlemi şifreli kart bilgisi uzunluğu aşıldı' },
    { code: 'CREDIT_UNIQUE_NUMBER_IS_REQUIRED', description: 'Kredi işlemi kart tekil bilgisi zorunludur' },
    { code: 'CREDIT_BIN_NUMBER_IS_REQUIRED', description: 'Kredi işlemi kart BIN bilgisi zorunludur' },
    { code: 'CREDIT_MASKED_NUMBER_IS_REQUIRED', description: 'Kredi işlemi maskeli kart bilgisi zorunludur' },
    { code: 'ENCRYPTED_OLD_CARD_NUMBER_AND_EXPIRE_DATE_IS_REQUIRED', description: 'Eski card son kullanma tarihi zorunlu alan' },
    { code: 'ENCRYPTED_NEW_CARD_NUMBER_AND_EXPIRE_DATE_IS_REQUIRED', description: 'Yeni card son kullanma tarihi zorunlu alan' },
    { code: 'OLD_CARD_NUMBER_MAX_LENGTH_EXCEEDED', description: 'Eski kart max limit aşıldı' },
    { code: 'NEW_CARD_NUMBER_MAX_LENGTH_EXCEEDED', description: 'Yeni kart max limit aşıldı' },
    { code: 'ISSUER_ICA_IS_REQUIRED', description: 'Issuer Ica doldurulması zorunludur' },
    { code: 'ISSUER_ICA_IS_NOT_VALID', description: 'Issuer ICA hatalıdır' },
    { code: 'OLD_EXPIRY_DATE_IS_NOT_VALID', description: 'Eski kart geçerlilik süresi hatalıdır' },
    { code: 'NEW_EXPIRY_DATE_IS_NOT_VALID', description: 'Yeni kart geçerlilik süresi hatalıdır' },
    { code: 'OLD_CARD_NUMBER_IS_NOT_VALID', description: 'Eski kart numarası hatalıdır' },
    { code: 'NEW_CARD_NUMBER_IS_NOT_VALID', description: 'Yeni kart numarası hatalıdır.' },
    { code: 'NEW_CARD_EXPIRY_DATE_MUST_BE_FUTURE_DATE', description: 'Yeni kart geçerlilik süresi bugünden büyük olmalıdır' },
    { code: 'CARD_ID_IS_REQUIRED', description: 'Kart ID gerekli' },
    { code: 'CARD_ID_MAX_LENGTH_EXCEEDED', description: 'Kart ID 353 haneden kısa olmalı' },
    { code: 'PAN_FORMAT_IS_NOT_VALID', description: 'Kart numarası formatı geçersiz' },
    { code: 'REWARD_LIST_MISMATCH', description: 'İstekte gönderilen ödül listesi, ilk istekte gönderilen ödül listesinden farklıdır' },
    { code: 'ORDER_PRICE_AMOUNT_MISMATCH', description: 'Sipariş detaylarında gönderilen değerlerin toplamı gönderilen ücret miktarı ile uyuşmamaktadır' },
    { code: 'ACCOUNT_KEY_MISMATCH', description: 'İstekte gönderilen hesap anahtarı, ilk işlemde gönderilen hesap anahtarından farklı' },
    { code: 'AMOUNT_MISMATCH', description: 'İstekte gönderilen tutar bilgisi, ilk işlemde gönderilen tutar bilgisinden farklı' },
    { code: 'CURRENCY_CODE_IS_NOT_VALID', description: 'Döviz kodu geçersiz' },
    { code: 'CURRENCY_CODE_IS_REQUIRED', description: 'Para birimi (döviz kodu) gerekli.' },
    { code: 'CURRENCY_CODE_LENGTH_IS_NOT_VALID', description: 'Para birimi (döviz kodu) 3 haneli olarak girilmeli' },
    { code: 'ICA_NUMBER_IS_NOT_VALID', description: 'ICA numarası geçersiz' },
    { code: 'ICA_NUMBER_MAX_LENGTH_EXCEEDED', description: 'ICA numarası 7 haneden kısa olmalı' },
    { code: 'INSTALLMENT_COUNT_MISMATCH', description: 'İstekte gönderilen taksit sayısı, ilk işlemde gönderilen taksit sayısından farklı' },
    { code: 'ACCOUNT_STATE_IS_NOT_VALID', description: 'Account durumu geçersiz' },
    { code: 'CARD_STATE_IS_NOT_VALID', description: 'Kart durumu geçersiz' },
    { code: 'CAMPAIGN_TYPE_IS_NOT_VALID', description: 'Kampanya tipi geçersiz' },
    { code: 'ORDER_NO_MAX_LENGTH_EXCEEDED', description: 'Sipariş numarası 65 karakterden kısa olmalı' },
    { code: 'ORDER_NO_MISMATCH', description: 'Sipariş no eşleşmedi' },
    { code: 'ORDER_NO_IS_REQUIRED', description: 'Sipariş no gerekmektedir' },
    { code: 'TERMINAL_GROUP_ID_IS_REQUIRED', description: 'Terminal grup no gerekli' },
    { code: 'TERMINAL_GROUP_ID_MAX_LENGTH_EXCEEDED', description: 'Terminal grup no gerekli' },
    { code: 'TERMINAL_GROUP_ID_IS_NOT_VALID', description: 'Terminal grup no gecerli değil' },
    { code: 'TERMINAL_GROUP_ID_MISMATCH', description: 'İstekte gönderilen terminal grup numarası, ilk işlemde gönderilen terminal grup numarasından farklı' },
    { code: 'VFT_CODE_MAX_LENGTH_EXCEEDED', description: 'VFT kodu 21 karakterden kısa olmalı' },
    { code: 'REWARD_NAME_MAX_LENGTH_EXCEEDED', description: 'Ödül adı 65 haneden kısa olmalı' },
    { code: 'REWARD_AMOUNT_IS_REQUIRED', description: 'Ödül miktarı gerekli' },
    { code: 'REWARD_AMOUNT_IS_NOT_VALID', description: 'Ödül miktarı geçersiz' },
    { code: 'ORDER_SHIPPING_IS_NOT_VALID', description: 'Kargo tutarı geçersiz' },
    { code: 'ORDER_PRICE_IS_REQUIRED', description: 'Sipariş tutarı gerekli' },
    { code: 'ORDER_PRICE_IS_NOT_VALID', description: 'Sipariş tutarı geçersiz' },
    { code: 'ORDER_DISCOUNT_IS_NOT_VALID', description: 'İndirim tutarı geçersiz' },
    { code: 'ORDER_DATE_IS_REQUIRED', description: 'Sipariş tarihi gerekli' },
    { code: 'ORDER_DATE_IS_NOT_VALID', description: 'Sipariş tarihi YYMMDD formatında olmalı' },
    { code: 'INSTALLMENT_COUNT_MAX_LIMIT_EXCEEDED', description: 'Taksit sayısı 99 değerinden küçük veya eşit olmalı' },
    { code: 'REWARD_AMOUNT_MAX_LIMIT_EXCEEDED', description: 'Reward amount 10 haneden kısa olmalı' },
    { code: 'ICA_NUMBER_MISMATCH', description: 'İstekte gönderilen ica number, ilk istekte gönderilen ica number\'dan farklıdır' },
    { code: 'PAYMENT_TYPE_IS_NOT_VALID', description: 'Ödeme tipi geçersiz' },
    { code: 'SECURE_3D_MODEL_IS_NOT_VALID', description: '3d modeli geçersiz' },
    { code: 'RECURRING_PRODUCT_ID_MAX_LENGTH_EXCEEDED', description: 'Tekrarlı ödeme talimatı tekil değeri 32 karaktere eşit veya kısa olmalıdır' },
    { code: 'CARD_EXPIRATION_DATE_IS_REQUIRED', description: 'Kart son kullanım tarihi gerekli' },
    { code: 'CARD_EXPIRATION_DATE_IS_NOT_VALID', description: 'Kart son kullanım tarihi geçersiz' },
    { code: 'CVC_MAX_LENGTH_EXCEEDED', description: 'Cvc 500 karakterden kısa olmalıdır' },
    { code: 'TERMINAL_IS_REQUIRED', description: 'Terminal bilgisi gereklidir' },
    { code: 'TERMINAL_ICA_NUMBER_IS_REQUIRED', description: 'Terminal Ica Numarası zorunludur' },
    { code: 'ACCOUNT_KEY_TYPE_IS_REQUIRED', description: 'Hesap anahtar türü gereklidir' },
    { code: 'SENDER_CARD_ALIAS_IS_REQUIRED', description: 'Gönderen kart adı gereklidir' },
    { code: 'RECIPIENT_CARD_ALIAS_IS_REQUIRED', description: 'Alıcı kart adı gereklidir' },
    { code: 'CARD_UNIQUE_ID_IS_REQUIRED', description: 'Card unique ID gerekli' },
    { code: 'CARD_UNIQUE_ID_MAX_LENGTH_EXCEEDED', description: 'Card unique ID 66 haneden kısa olmalı' },
    { code: 'ENCRYPTED_CARD_NUMBER_IS_REQUIRED', description: 'Şifrelenmiş kart numarası gerekli' },
    { code: 'ICA_NUMBER_IS_REQUIRED', description: 'ICA numarası gerekli' },
    { code: 'INSTALLMENT_COUNT_IS_NOT_VALID', description: 'Taksit sayısı geçersiz' },
    { code: 'CAMPAIGN_CODE_IS_NOT_VALID', description: 'Kampanya kodu geçersiz' },
    { code: 'MASKED_CARD_NUMBER_IS_REQUIRED', description: 'Maskelenmiş kart numarası gerekli' },
    { code: 'MASKED_CARD_NUMBER_MAX_LENGTH_EXCEEDED', description: 'Maskelenmiş kart numarası 21 karakterden kısa olmalı' },
    { code: 'RETRIEVAL_REFERENCE_NUMBER_IS_REQUIRED', description: 'Retrieval reference number gerekli' },
    { code: 'RETRIEVAL_REFERENCE_NUMBER_IS_NOT_VALID', description: 'Retrieval reference number geçersiz' },
    { code: 'CITIZENSHIP_NUMBER_REQUIRED', description: 'Kimlik numarası gerekli' },
    { code: 'OTP_CODE_IS_REQUIRED', description: 'Tek seferlik şifre gerekli' },
    { code: 'OTP_CODE_MAX_LENGTH_EXCEEDED', description: 'Tek seferlik şifre uzunluğu 21 karakterden az olmalı' },
    { code: 'CITIZENSHIP_NUMBER_IS_NOT_VALID', description: 'Kimlik numarası geçersiz' },
    { code: 'CITIZENSHIP_NUMBER_MAX_LENGTH', description: 'Kimlik numarası 11 hane olmalı' }
  ];

  // VPOS / Acquirer Error Codes
  vposErrorCodes: ErrorCode[] = [
    { code: 'ALREADY_REFUNDED', description: 'İşlem iade durumunda veya iade edilmek istenen tutar satış tutarından büyük' },
    { code: 'CANNOT_BE_REFUNDED', description: 'İade tutarını ve iade edilmek istenen işlem günsonuna girmediği kontrol edilmelidir' },
    { code: 'CANNOT_BE_VOIDED', description: 'Günsonuna giren işlem iptal edilemez' },
    { code: 'CARD_NOT_PERMITTED', description: 'Kart sahibi bankası ile iletişime geçmelidir' },
    { code: 'DAILY_REFUND_LIMIT_EXCEED', description: 'Günlük iade limiti aşılmıştır' },
    { code: 'DECLINED', description: 'Ödeme işlemi tamamlanamadı' },
    { code: 'DO_NOT_HONOUR', description: 'Banka hatası' },
    { code: 'EMPTY_PARAMETER', description: 'Zorunlu parametrelerden biri gönderilmedi' },
    { code: 'EXCEED_PIN_TRIES', description: 'PIN giriş sayısı aşıldı' },
    { code: 'EXCEEDS_WITHDRAWAL_LIMIT', description: 'Para çekme limiti aşıldı' },
    { code: 'EXPIRED_CARD', description: 'Son kullanım tarihi hatalıdır' },
    { code: 'GENERAL_BANK_ERROR', description: 'Basarisiz işlem, Genel banka hatası oluştu' },
    { code: 'HONOUR_WITH_ID', description: 'Banka hatası' },
    { code: 'INSUFFICIENT_FUNDS', description: 'Yetersiz bakiye' },
    { code: 'INTERNAL_ERROR', description: 'Beklenmedik hata' },
    { code: 'INVALID_AMOUNT', description: 'İşlem tutarı kontrol edilmelidir.' },
    { code: 'INVALID_CARD_NUMBER', description: 'Kart numarası hatalı girilmiş veya kart kaydı yok' },
    { code: 'INVALID_ECI_CAVV', description: 'ECI ve CAVV değerlerinin provizyon mesajında boş veya hatalı gönderilmektedir' },
    { code: 'INVALID_EXPIRE_DATE', description: 'Kart vadesi hatalı veya vade formatı hatalı' },
    { code: 'INVALID_MID_TID_IP', description: 'Bağlantı yaparken kullandığınız mid (üye işyeri no) yanlış veya izin verilmemiş bir ip\'den bağlantı yapılıyor' },
    { code: 'INVALID_PARAMETER', description: 'Hatalı parametre' },
    { code: 'INVALID_PIN', description: 'Geçersiz PIN. Banka ile iletişime geçilmelidir' },
    { code: 'INVALID_ROUTING', description: 'Finansal kurum taninmiyor' },
    { code: 'INVALID_SECURITY_CODE', description: 'Hatalı CVC/CVV' },
    { code: 'INVALID_TRANSACTION', description: 'Geçersiz işlem. Kart bilgilerini ve yetkilerini kontrol edebilir, sorun devam ediyorsa bankası ile görüşebilir' },
    { code: 'ISSUER_UNAVAILABLE', description: 'Kart bankası işleme cevap vermiyor' },
    { code: 'LOST_CARD', description: 'Kayıp kart, karta el koyunuz' },
    { code: 'MERCHANT_CREDENTIAL_NOT_FOUND', description: 'Üye işyeri bilgileri hatalı' },
    { code: 'MERCHANT_CREDENTIALS_NOT_FOUND', description: 'Üye işyeri bilgileri hatalı' },
    { code: 'NEGOTIATION_ERROR', description: 'Günsonu Hatası' },
    { code: 'NO_SUCH_ISSUER', description: 'Kredi kartı bilgilerinin kontrol edilmesi gerekiyor. Ödeme sistemlerinde tanımlı olmayan kart ile işlem yapılıyor olabilir' },
    { code: 'NOT_ALLOWED_FOR_INSTALLMENT', description: 'Taksit tanımı yok veya denenen işlem tutarı 1 TL nin altındadır' },
    { code: 'NOT_APPROVED', description: 'Kart sahibi bankasından detaylı bilgi alabilir, veya farklı kart ile deneme yapabilir' },
    { code: 'NOT_PERMITTED_CARDHOLDER', description: 'Kart sahibi bankası ile iletişime geçmelidir' },
    { code: 'NOT_PERMITTED_FOR_E-COMMERCE', description: 'Kartınız e-ticaret işlemlerine kapalıdır' },
    { code: 'NOT_PERMITTED_TO_TERMINAL', description: 'İşlem tipi için pos yetkilerinin kontrol edilmesi gereklidir' },
    { code: 'ORDER_ALREADY_VOIDED', description: 'İşlem iptal durumunda' },
    { code: 'ORDER_NO_ALREADY_USED', description: 'Sipariş numarası daha önce kullanılmıştır' },
    { code: 'PICKUP_CARD', description: 'Kart bankası tarafından kullanıma kapatılmıştır, kart sahibi kredi kartı bankasından bilgi alabilir' },
    { code: 'PREAUTH_ALREADY_CANCELLED', description: 'Preauth işlemi zaten iptal edilmiş' },
    { code: 'REFER_TO_CARD_ISSUER', description: 'Kart sahibi bankasından onay almalıdır' },
    { code: 'RESTRICTED_CARD', description: 'Kart işleme kısıtlanmış' },
    { code: 'SECURITY_VIOLATION', description: 'Banka tarafından güvenlik sebebiyle reddedilmiştir' },
    { code: 'STOLEN_CARD', description: 'Çalıntı kart, karta el koyunuz' },
    { code: 'SYSTEM_ERROR', description: 'Banka genel sistem hatası' },
    { code: 'TRANSACTION_IN_PROGRESS', description: 'İşlem devam ediyor' },
    { code: 'TRANSACTION_NOT_FOUND', description: 'Orderid ye ait bir kayıt bulunamadı' },
    { code: 'TRANSACTION_REQUIRED_3DS', description: '3D secure ödeme yapılmalıdır' },
    { code: 'VPOS_TIMEOUT_ERROR', description: 'Banka beklenen sürede cevap veremedi' },
    { code: '3DS_AUTH_ERROR', description: '3D Doğrulama hatası' }
  ];

  openModal() {
    this.showModal = true;
  }

  closeModal() {
    this.showModal = false;
  }

  onBackdropClick(event: MouseEvent) {
    if ((event.target as HTMLElement).classList.contains('modal-backdrop')) {
      this.closeModal();
    }
  }

  toggleBusiness() {
    this.businessExpanded = !this.businessExpanded;
  }

  toggleValidation() {
    this.validationExpanded = !this.validationExpanded;
  }

  toggleVpos() {
    this.vposExpanded = !this.vposExpanded;
  }
}
